### ISSUE TITLE
Issue reading data from a specific provider

### ISSUE THREAD

**Issue by da-br** [nmangue/NGrib#25]
Hello,

Sorry for the lack of information here, but I am quite stumped. 

I have a grb2 file that is failing to read some datasets. I have created a PR [here](https://github.com/nmangue/NGrib/pull/24), which has two failing tests demonstrating the error.

The two tests crash at different points.

Panoply can open these variables, so I don't believe the problem is in the data file. 

Thanks :)

**Comment by nmangue** [comment]
Hello,

Well, you're in luck ! (Or sort of ^^) The error occurs in the grid point data decoding, which uses the Complex packing and spatial differencing data representation (template 5.3). 
#23 is also an issue on this format. As a fix, I just completely rewrote the unpack function. This seems to also fix your file decoding. I have quickly ran your unit tests and it seems ok. The only mismatch I get is on the average value check. I get a value of -0.67744476 instead of ~-0.0677. Could it be a typo ?
It would be great if you could you rerun your test using branch fix/issue-23.

**Comment by da-br** [comment]
Thanks so much!

I've rerun the tests and am happy with the result, the extra 0 must have been a typo.

**Comment by da-br** [comment]
Is there an update on getting #23 merged?

**Comment by FranzThomsen1089** [comment]
@nmangue I would love for this to be merged in :)

**Comment by nmangue** [comment]
Fixed with the release of v0.12.0
